### ISSUE TITLE
Crashes when there is no internet connection

### ISSUE THREAD

**Issue by probonopd** [clipr/clipr#1]
Seems like this crashes when there is no internet connection, at least we get no screenshot.

The expected behavior would be that at least a GUI error message comes up.

```
firejail ./BeingTested.AppImage /run/firejail/appimage/.appimage-10012/AppRun: line 214: gtk-update-icon-cache: command not found
Xlib:  extension "RANDR" missing on display ":99".
setting tray icon /run/firejail/appimage/.appimage-10012/assets/icons/tray/clipr_tray.png
setting app icon: /run/firejail/appimage/.appimage-10012/assets/icons/512.png
app is ready
Checking for update
Generated new staging user ID: 75194bfd-aadc-51e1-9e2f-46826b2dd161
Error: Error: net::ERR_INTERNET_DISCONNECTED
    at CancellationToken.createPromise (/run/firejail/appimage/.appimage-10012/resources/app.asar/node_modules/builder-util-runtime/src/CancellationToken.ts:51:12)
    at ElectronHttpExecutor.doApiRequest (/run/firejail/appimage/.appimage-10012/resources/app.asar/node_modules/builder-util-runtime/src/httpExecutor.ts:84:30)
    at ElectronHttpExecutor.request (/run/firejail/appimage/.appimage-10012/resources/app.asar/node_modules/builder-util-runtime/src/httpExecutor.ts:74:17)
    at GitHubProvider.httpRequest (/run/firejail/appimage/.appimage-10012/resources/app.asar/node_modules/electron-updater/src/providers/Provider.ts:29:26)
    at /run/firejail/appimage/.appimage-10012/resources/app.asar/node_modules/electron-updater/src/providers/GitHubProvider.ts:38:41
    at Generator.next (<anonymous>)
From previous event:
    at GitHubProvider.getLatestVersion (/run/firejail/appimage/.appimage-10012/resources/app.asar/node_modules/electron-updater/src/providers/GitHubProvider.ts:35:25)
    at /run/firejail/appimage/.appimage-10012/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:345:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at AppImageUpdater.getUpdateInfo (/run/firejail/appimage/.appimage-10012/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:335:32)
    at /run/firejail/appimage/.appimage-10012/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:349:35
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.doCheckForUpdates (/run/firejail/appimage/.appimage-10012/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:348:34)
    at /run/firejail/appimage/.appimage-10012/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:287:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at AppImageUpdater._checkForUpdates (/run/firejail/appimage/.appimage-10012/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:282:33)
    at AppImageUpdater.checkForUpdates (/run/firejail/appimage/.appimage-10012/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:221:35)
    at AppImageUpdater.checkForUpdatesAndNotify (/run/firejail/appimage/.appimage-10012/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:235:41)
    at AppImageUpdater.checkForUpdatesAndNotify (/run/firejail/appimage/.appimage-10012/resources/app.asar/node_modules/electron-updater/src/AppImageUpdater.ts:33:18)
    at EventEmitter.ready (/run/firejail/appimage/.appimage-10012/resources/app.asar/main.js:53:21)
    at emitNone (events.js:106:13)
    at EventEmitter.emit (events.js:208:7)
    at App.appReady (/run/firejail/appimage/.appimage-10012/resources/app.asar/menubar.js:98:17)
    at emitTwo (events.js:131:20)
    at App.emit (events.js:214:7)
    at App.emitter.emit.args [as emit] (/run/firejail/appimage/.appimage-10012/resources/app.asar/node_modules/@sentry/electron/src/main/backend.ts:325:14)
Error: net::ERR_INTERNET_DISCONNECTED
shortcut registered: true
Error: net::ERR_INTERNET_DISCONNECTED
Error: net::ERR_INTERNET_DISCONNECTED
```

Reference:
https://github.com/AppImage/appimage.github.io/pull/985

**Comment by zisismaras** [comment]
It was crashing while checking for updates, it should be fixed on the latest release.

If you are still unable to get an automated screenshot (since the app starts minimized on the tray) you could use the images in the readme.

Thanks!
